#-----------------------------------------------------------------------------
#
#  TSDuck - The MPEG Transport Stream Toolkit
#  Copyright (c) 2005-2025, Thierry Lelegard, Sergey Lobanov
#  BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#  GitHub Actions configuration file : Address Sanitizer
#
#-----------------------------------------------------------------------------

name: Address Sanitizer

on:
  workflow_dispatch:

jobs:
  build_unix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler: [gcc]
        std: [20]
    name: Sanitizer on ${{ matrix.os }} with ${{ matrix.compiler }}, C++${{ matrix.std }}
    runs-on: ${{ matrix.os }}
    env:
      BINDIR: bin
      ASAN: true
      ASAN_RUN: true
      CXXFLAGS_STANDARD: -std=c++${{ matrix.std }}
      ORIGIN_REPO: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      REFERENCE_REPO: tsduck/tsduck
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          scripts/install-prerequisites.sh
          ${{ matrix.compiler }} --version
      - name: Build TSDuck
        run: make -j5
      - name: Check built version
        run: make show-version
      - name: Run unitary tests
        run: make test
      - name: Download test suite
        run: |
          # Try to download '<repo>-test' from the pull request owner, if there is one.
          if curl -fsL "https://github.com/${ORIGIN_REPO}-test/tarball/master" -o test.tgz; then
              echo "Downloaded test suite from $ORIGIN_REPO"
          else
              curl -fsL "https://github.com/${REFERENCE_REPO}-test/tarball/master" -o test.tgz
              echo "Downloaded test suite from $REFERENCE_REPO"
          fi
          mkdir -p ../tsduck-test
          tar -C ../tsduck-test -x -z -f test.tgz --strip 1
      - name: Run test suite
        run: |
          make test-suite && status=$? || status=$?
          cd ../tsduck-test
          for f in $(find tmp -name '*.diff'); do
              echo "==== $f";
              cat "$f"
          done
          exit $status
