#-----------------------------------------------------------------------------
#
#  TSDuck - The MPEG Transport Stream Toolkit
#  Copyright (c) 2005-2025, Thierry Lelegard
#  BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#  GitHub Actions configuration file : Build Ubuntu
#
#  Build installer for Ubuntu on request (workflow dispatch)
#
#-----------------------------------------------------------------------------

name: Build Ubuntu Package

on:
  # Manual trigger only, with target runner selection.
  workflow_dispatch:
    inputs:
      system:
        type: choice
        description: 'Target system'
        required: true
        default: 'ubuntu-latest'
        options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-24.04-arm
        - ubuntu-22.04-arm

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.system }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Get TSDuck repo
      uses: actions/checkout@master

    - name: Install dependencies
      run: scripts/install-prerequisites.sh

    - name: Build TSDuck
      run: |
        fullversion=$(scripts/get-version-from-sources.py --full)
        arch=$(dpkg-architecture -qDEB_BUILD_ARCH)
        echo "FULLVERSION=$fullversion" >>$GITHUB_ENV
        echo "ARCH=$arch" >>$GITHUB_ENV
        make installer

    - name: Upload Ubuntu package
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-package
        path: pkg/installers/tsduck_${{ env.FULLVERSION }}_${{ env.ARCH }}.deb
        retention-days: 5

    - name: Upload Ubuntu dev package
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-dev-package
        path: pkg/installers/tsduck-dev_${{ env.FULLVERSION }}_${{ env.ARCH }}.deb
        retention-days: 5
