#-----------------------------------------------------------------------------
#
#  TSDuck - The MPEG Transport Stream Toolkit
#  Copyright (c) 2005-2025, Thierry Lelegard
#  BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#  GitHub Actions configuration file : Build Windows
#
#  Build installer for Windows on request (workflow dispatch)
#
#-----------------------------------------------------------------------------

name: Build Windows Package

on:
  # Manual trigger only, with target system selection.
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Target system'
        required: true
        default: 'Win64'
        options:
        - Win64
        - Win32
        - Arm64

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Get TSDuck repo
      uses: actions/checkout@master

    - name: Install dependencies
      run: scripts/install-prerequisites.ps1 -GitHubActions -NoDoxygen -NoPause

    - name: Build TSDuck
      run: |
        $version = (python scripts\get-version-from-sources.py)
        Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        pkg/nsis/build-installer.ps1 -${{ inputs.target }} -NoPause -NoLowPriority

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: pkg/installers/TSDuck-${{ inputs.target }}-${{ env.VERSION }}.exe
        retention-days: 5

    - name: Upload portable
      uses: actions/upload-artifact@v4
      with:
        name: portable
        path: pkg/installers/TSDuck-${{ inputs.target }}-${{ env.VERSION }}-Portable.zip
        retention-days: 5
