#-----------------------------------------------------------------------------
#
#  TSDuck - The MPEG Transport Stream Toolkit
#  Copyright (c) 2005-2025, Thierry Lelegard
#  BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#  GitHub Actions configuration file : Release subworkflow.
#
#  Do not start this workflow manually, this is a subworkflow of release.yml.
#  This subworkflow must be technically separated from release.yml because of
#  a limitation in GitHub Actions: "matrix" cannot be used from "jobs.job.if".
#  See https://github.com/orgs/community/discussions/37883
#
#-----------------------------------------------------------------------------

name: Release subworkflow

on:
  workflow_call:
    inputs:
      build:
        # Not really a description of this input. Intended to be displayed
        # in the UI if the user wants to run this subworkflow manually.
        description: 'Do not start this workflow manually, this is a subworkflow of Release'
        required: true
        type: boolean
      arch:
        required: true
        type: string
      distro:
        required: true
        type: string
      runner:
        required: true
        type: string
      image:
        required: true
        type: string
      initial:
        type: string
      package_options:
        type: string

jobs:
  build:
    if: inputs.build
    name: Build in container
    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.image }}
    steps:
    - name: Initial container setup
      run: ${{ inputs.initial }}
    - name: Get TSDuck repo
      uses: actions/checkout@master
#@@    - name: Build
    #--------------------------------------------------------------
    - name: Fake build #@@
      run: |
        sudo apt install -y python3
        V=$(python3 scripts/get-version-from-sources.py)
        if [[ ${{ inputs.distro }} == ubuntu && ${{ inputs.arch }} == x64 ]]; then
          TOOLSP=tsduck_$V.ubuntu24_amd64.deb
          DEVP=tsduck-dev_$V.ubuntu24_amd64.deb
        elif [[ ${{ inputs.distro }} == ubuntu && ${{ inputs.arch }} == arm64 ]]; then
          TOOLSP=tsduck_$V.ubuntu24_arm64.deb
          DEVP=tsduck-dev_$V.ubuntu24_arm64.deb
        elif [[ ${{ inputs.distro }} == debian && ${{ inputs.arch }} == x64 ]]; then
          TOOLSP=tsduck_$V.debian13_amd64.deb
          DEVP=tsduck-dev_$V.debian13_amd64.deb
        elif [[ ${{ inputs.distro }} == debian && ${{ inputs.arch }} == arm64 ]]; then
          TOOLSP=tsduck_$V.debian13_arm64.deb
          DEVP=tsduck-dev_$V.debian13_arm64.deb
        elif [[ ${{ inputs.distro }} == fedora && ${{ inputs.arch }} == x64 ]]; then
          TOOLSP=tsduck-$V.fc42.x86_64.rpm
          DEVP=tsduck-devel-$V.fc42.x86_64.rpm
        elif [[ ${{ inputs.distro }} == fedora && ${{ inputs.arch }} == arm64 ]]; then
          TOOLSP=tsduck-$V.fc42.aarch64.rpm
          DEVP=tsduck-devel-$V.fc42.aarch64.rpm
        elif [[ ${{ inputs.distro }} == redhat && ${{ inputs.arch }} == x64 ]]; then
          TOOLSP=tsduck-$V.el9.x86_64.rpm
          DEVP=tsduck-devel-$V.el9.x86_64.rpm
        elif [[ ${{ inputs.distro }} == redhat && ${{ inputs.arch }} == arm64 ]]; then
          TOOLSP=tsduck-$V.el9.aarch64.rpm
          DEVP=tsduck-devel-$V.el9.aarch64.rpm
        fi
        echo fake >pkg/installers/$TOOLSP
        echo fake >pkg/installers/$DEVP
        ls -l pkg/installers
    #--------------------------------------------------------------
    - name: List installers
      run: |
        ls -l pkg/installers
        PACKS=($(ls pkg/installers | sort -d | grep -e '\.deb$' -e '\.rpm$'))
        echo "Tools package: ${PACKS[0]}"
        echo "Dev package: ${PACKS[1]}"
        echo "TSTOOLS=${PACKS[0]}" >>$GITHUB_ENV
        echo "TSDEV=${PACKS[1]}" >>$GITHUB_ENV
    - name: Publish tools package
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-${{ inputs.distro }}-${{ inputs.arch }}
        path: pkg/installers/${{ env.TSTOOLS }}
        retention-days: 5
    - name: Publish dev package
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-dev-${{ inputs.distro }}-${{ inputs.arch }}
        path: pkg/installers/${{ env.TSDEV }}
        retention-days: 5
