#-----------------------------------------------------------------------------
#
#  TSDuck - The MPEG Transport Stream Toolkit
#  Copyright (c) 2005-2025, Thierry Lelegard
#  BSD-2-Clause license, see LICENSE.txt file or https://tsduck.io/license
#
#  GitHub Actions configuration file : Create a release.
#
#  Generate binaries for Ubuntu, Debian, Fedora, Red Hat, and Windows
#  on Intel x64 and Arm64. The Linux binaries are built on Docker
#  containers running a Ubunty GitHub runner host. All binaries are
#  published as artifacts of the workflow.
#
#-----------------------------------------------------------------------------

name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Create release after build'
        type: choice
        required: true
        default: 'none'
        options:
        - none
        - update-last
        - draft
        - pre-release
        - official
      build_x64:
        description: 'Build Intel x64 packages'
        type: boolean
        required: true
        default: true
      build_arm64:
        description: 'Build Arm64 packages'
        type: boolean
        required: true
        default: true
      build_windows:
        description: 'Build Windows packages'
        type: boolean
        required: true
        default: true
      ubuntu_image:
        description: 'Ubuntu docker image'
        type: choice
        required: true
        default: 'ubuntu:latest'
        options:
        - none
        - ubuntu:latest
        - ubuntu:25.04
      debian_image:
        description: 'Debian docker image'
        type: choice
        required: true
        default: 'debian:trixie'
        options:
        - none
        - debian:latest
        - debian:trixie
      fedora_image:
        description: 'Fedora docker image'
        type: choice
        required: true
        default: 'fedora:latest'
        options:
        - none
        - fedora:latest
        - fedora:42
      redhat_image:
        description: 'Red Hat docker image'
        type: choice
        required: true
        default: 'almalinux:latest'
        options:
        - none
        - almalinux:latest
        - rockylinux:9

jobs:
  # Initial job: get latest release tag if release_type is "update-last"
  getlatest:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install prerequisites
      if: ${{ inputs.release_type == 'update-last' }}
      run: sudo apt install -y curl jq
    - name: Get latest version tag
      id: get_tag
      run: |
        if [[ ${{ inputs.release_type }} == update-last ]]; then
            tag=$(curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
            tag=${tag/#null/}
            echo "Tag to build: $tag"
        else
            tag=
            echo "Build the latest commit"
        fi
        echo "tag=$tag" >> "$GITHUB_OUTPUT"

  linux:
    needs: [getlatest]
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu, debian, fedora, redhat]
        arch: [x64, arm64]
        include:
        - arch: x64
          build_arch: ${{ inputs.build_x64 }}
          runner: ubuntu-latest
        - arch: arm64
          build_arch: ${{ inputs.build_arm64 }}
          runner: ubuntu-24.04-arm
        - distro: ubuntu
          build_distro: ${{ inputs.ubuntu_image != 'none' }}
          image: ${{ inputs.ubuntu_image }}
          install_command: apt install -y
          initial: apt update; apt install -y sudo git lsb-release
          package_options:
        - distro: debian
          build_distro: ${{ inputs.debian_image != 'none' }}
          image: ${{ inputs.debian_image }}
          install_command: apt install -y
          initial: apt update; apt install -y sudo git lsb-release
          package_options:
        - distro: fedora
          build_distro: ${{ inputs.fedora_image != 'none' }}
          image: ${{ inputs.fedora_image }}
          install_command: dnf install -y
          initial: dnf install -y sudo git
          package_options: --allowerasing
        - distro: redhat
          build_distro: ${{ inputs.redhat_image != 'none' }}
          image: ${{ inputs.redhat_image }}
          install_command: dnf install -y
          initial: dnf install -y sudo git
          package_options: --allowerasing
    name: Build on ${{ matrix.distro }} for ${{ matrix.arch }}
    # Complicated structure using one sub-workflow because "matrix" cannot be referenced from "jobs.job.if".
    # See https://github.com/orgs/community/discussions/37883
    uses: ./.github/workflows/release-one.yml
    with:
      build: ${{ matrix.build_arch && matrix.build_distro }}
      continue_on_error: ${{ inputs.release_type != 'none' }}
      tag: ${{ needs.getlatest.outputs.tag }}
      arch: ${{ matrix.arch }}
      distro: ${{ matrix.distro }}
      runner: ${{ matrix.runner }}
      image: ${{ matrix.image }}
      install_command: ${{ matrix.install_command }}
      initial: ${{ matrix.initial }}
      package_options: ${{ matrix.package_options }}
    secrets: inherit
    permissions:
      id-token: write
      contents: read

  windows:
    name: Build on windows
    if: ${{ inputs.build_windows && (inputs.build_x64 || inputs.build_arm64) }}
    needs: [getlatest]
    runs-on: windows-latest
    continue-on-error: ${{ inputs.release_type != 'none' }}
    steps:
    - name: Get TSDuck repo
      uses: actions/checkout@master
    - name: Install dependencies
      run: scripts\install-prerequisites.ps1 -GitHubActions -NoDoxygen -NoPause
    - name: Build
      run: pkg\nsis\build-installer.ps1 -Win64:$${{ inputs.build_x64 }} -Arm64:$${{ inputs.build_arm64 }} -NoLowPriority -NoPause
    - name: List installers
      run: |
        Get-ChildItem pkg\installers
        Write-Output ""
        if ($${{ inputs.build_x64 }}) {
            $TSW64 = (Get-ChildItem pkg\installers\TSDuck-Win64-*.exe).Name
            $TSW64P = (Get-ChildItem pkg\installers\TSDuck-Win64-*-Portable.zip).Name
            Write-Output "Win64 installer: $TSW64"
            Write-Output "Win64 portable: $TSW64P"
            Write-Output "TSW64=$TSW64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            Write-Output "TSW64P=$TSW64P" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }
        if ($${{ inputs.build_arm64 }}) {
            $TSA64 = (Get-ChildItem pkg\installers\TSDuck-Arm64-*.exe).Name
            $TSA64P = (Get-ChildItem pkg\installers\TSDuck-Arm64-*-Portable.zip).Name
            Write-Output "Arm64 installer: $TSA64"
            Write-Output "Arm64 portable: $TSA64P"
            Write-Output "TSA64=$TSA64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            Write-Output "TSA64P=$TSA64P" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }
    - name: Publish Win64 package
      if: ${{ inputs.build_x64 }}
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-windows-x64
        path: pkg/installers/${{ env.TSW64 }}
        retention-days: 5
    - name: Publish Win64 portable package
      if: ${{ inputs.build_x64 }}
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-windows-portable-x64
        path: pkg/installers/${{ env.TSW64P }}
        retention-days: 5
    - name: Publish Arm64 package
      if: ${{ inputs.build_arm64 }}
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-windows-arm64
        path: pkg/installers/${{ env.TSA64 }}
        retention-days: 5
    - name: Publish Arm64 portable package
      if: ${{ inputs.build_arm64 }}
      uses: actions/upload-artifact@v4
      with:
        name: tsduck-windows-portable-arm64
        path: pkg/installers/${{ env.TSA64P }}
        retention-days: 5

  release:
    name: Create the release
    if: ${{ inputs.release_type != 'none' }}
    needs: [linux, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get TSDuck repo
      uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt install -y python3-github
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: pkg/installers
    - name: Extract artifacts
      run: |
        cd pkg/installers
        for f in $(ls -d tsduck-*-x64 tsduck-*-arm64 2>/dev/null || true); do
            if [[ -d $f ]]; then
                mv $f/* .
                rmdir $f
            fi
        done
        ls -lR
    - name: Create the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating release in repository ${{ github.repository }}"
        case ${{ inputs.release_type }} in
            update-last) opt="--update" ;;
            draft)       opt="--create --missing --draft" ;;
            pre-release) opt="--create --missing --pre" ;;
            official)    opt="--create --missing" ;;
            *) echo "Invalid release_type: ${{ inputs.release_type }}"; exit 1 ;;
        esac
        pkg/github/release.py --repo ${{ github.repository }} $opt
